### ISSUE TITLE
Use svg mdi icons

### ISSUE THREAD

**Issue by holgerkoser** [gardener/dashboard#1223]
**What would you like to be added**:
https://vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg

> Use the SVG paths as designated in [@mdi/js](https://www.npmjs.com/package/@mdi/js). This is the recommended installation when optimizing your application for production. You ONLY need to include this if you plan on using more than the default icons.

```vue
<template>
  <v-icon>{{ svgPath }}</v-icon>
</template>

<script>
  import { mdiAccount } from '@mdi/js'

  export default {
    data: () => ({
      svgPath: mdiAccount
    }),
  }
</script>
```
**Why is this needed**:

**Comment by sven-petersen** [comment]
Major driver for this issue was to reduce bundle size. Unfortunately there are some places, such as custom fields, where users can specify any mdi icon. Hence it is necessary to always bundle all mdi icons with the application.

If all icons are needed, the icon font is more compact than its SVG representation. See file sizes here:
https://www.npmjs.com/package/@mdi/js?activeTab=explore
https://www.npmjs.com/package/@mdi/font?activeTab=explore

**Comment by petersutter** [comment]
The help menu items is another example where the dashboard admin can configure custom icons for the help menu entries https://github.com/gardener/dashboard/blob/7160a48ca8a3567e4cc32d1b804d8d86846cac37/charts/gardener-dashboard/values.yaml#L135-L141
