### ISSUE TITLE
Setup instructions for gardenctl and gardenlogin

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1314]
**What would you like to be added**:
The dashboard currently shows the gardenctl target commands for shoot clusters and the control plane, however there is no help shown on how to setup gardenlogin and gardenctl.

Also for #1168 it would be helpful to have such setup instructions.

**Why is this needed**:

**Comment by petersutter** [comment]
related issue https://github.com/gardener/gardenctl-v2/issues/182 will simplify the setup

**Comment by andrei-panov** [comment]
Hi @petersutter 
Here are two links with updated documentation:
1. https://github.tools.sap/kubernetes/ops-guide/blob/master/01_Operations/02_How_To_Guides/03_Other/Installing_Required_Tools_Locally.md#gardenctl
2. https://github.tools.sap/kubernetes/ops-guide/blob/master/02_Developer_On_Duty/04_Access/Configure_gardenctl_v2.md

It's a bit tricky, but the second link is published here https://pages.github.tools.sap/kubernetes/gardener/docs/015-guides/configure-gardenctl-v2/
And the first one will be published later I hope.
I adapted the documentation to make it universal for Mac & Linux & Windows users.

What do you think about providing the link on the Gardener operator dashboard? Should it lead to Internet-Public gardenctl install instruction or ... keep it as it is because of the public \ internal nature of the documentation?
