### ISSUE TITLE
Unclear reconcile message and icon for end users

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#166]
since yesterday I got feedback and questions from several stakeholder that the cluster seems to be unstable - After a few investigations, however, it turns out that the clusters are **100% operable**. *But where does the user's uncertainty come from?*

It seems that the icon, which indicates the reconcile, is the problem. It gives you the impression that something is happening/repairing because there is also a forklift in the icon. Additional the status TAG's are missing.

<img width="1056" alt="bildschirmfoto 2018-08-14 um 10 33 57" src="https://user-images.githubusercontent.com/1155039/44081325-c14a6344-9fae-11e8-93a3-a8e56dd463bb.png">

Why not stay the checkmark inside the icon during the reconcile? I think you should allow/use a green checkmark as long as you haven't found a problem.

<img width="1095" alt="bildschirmfoto 2018-08-14 um 10 49 12" src="https://user-images.githubusercontent.com/1155039/44081731-b73492ca-9faf-11e8-910b-372226229638.png">

**At the moment the users seems to have a problem with the current UX pattern.**

**Comment by grolu** [comment]
Hi,
the status tags are set by the gardener, we cannot influence this. During reconcile they become unavailable but nothing changed in this behavior recently. Likewise, it is nothing new that clusters are getting reconciled from time to time. Previously, we showed the progress as percentage instead of the tractor icon. While we can discuss if a tractor is the best icon to indicate that a reconcile operation is running, I do not fully understand why this minor change causes that much confusion. As I already pointed out, also in previous releases the status tags were gone during reconcile and a progress was shown instead of the checkmark icon...

**Comment by freegroup** [comment]
This is the *problem* with UX. minor changes can have a big impact. :-)
In the end, I get notified that the gardener seems to have a problem right now...

**Comment by grolu** [comment]
I think the main issue is that during reconciliation the status tags are not visible. @rfranzke is there a technical reason for this? Could we not keep the last state and only replace it with an updated state after reconciliation? This way, the buttons would not disappear.

**Comment by vlerenc** [comment]
That would indeed be helpful. As long as the reconciler has not found issues, the last known status should be shown. That also goes the other way, i.e. whether it was healthy or unhealthy before.
Not sure how difficult it would be and what needs to be considered, but from usability PoV, it would definitely be preferable.

**Comment by grolu** [comment]
@rfranzke We discussed this topic in our UI sync with @vlerenc. May you have another look at the code and change the logic to not remove the labels during reconciliation? This would be very helpful to reduce confusion for the users
@freegroup In addition, we decided to change the tractor to a blue checkmark with a progress during reconciliation.

**Comment by rfranzke** [comment]
I don't really remember why we disabled the health check while an operation is processing. We might have taken this decision because of this one: If we remove this behaviour the care controller doing the health check would also start its work for newly created clusters and for cluster which are to be deleted or currently in the deletion process. In those cases most of the checks will fail and appear red in the UI. I guess we assumed that this would generate more confusion than just not doing the checks while an operation is in progress.

**Comment by grolu** [comment]
So we changed the icon in our upcoming release:
<img width="1114" alt="screen shot 2018-09-19 at 08 56 02" src="https://user-images.githubusercontent.com/35373687/45736013-0676f200-bbea-11e8-9684-c2f90b9a85a7.png">
In case of an error during reconcile, an exclamation mark will replace the checkmark:
<img width="1095" alt="screen shot 2018-09-19 at 08 55 39" src="https://user-images.githubusercontent.com/35373687/45736066-2c9c9200-bbea-11e8-9612-4aa40c761674.png">

As you can see, the readiness tags are still not visible during reconcile. @rfranzke, @vlerenc any final thoughts on this before I close this issue?

**Comment by vlerenc** [comment]
@Adracus is working on this, i.e. preserving the conditions while reconciling and only changing the conditions, when the condition indeed changes.
