### ISSUE TITLE
*hidden* feature of cluster upgrade

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#167]
The basic setting of the overview does not include the version of the Kubernetes Cluster. It is therefore not possible for the user to see if an Update of the Cluster is possible or not. Furthermore, one of the strengths of the Gardener is that it can migrate a Cluster. However, this core feature is very, very hidden and not obvious to the end user.

## Default overview
<img width="1230" alt="bildschirmfoto 2018-08-14 um 14 15 18" src="https://user-images.githubusercontent.com/1155039/44091199-f4c1570a-9fcc-11e8-9e0f-7324f062fd24.png">

## Customized view with the **version** attribute
<img width="963" alt="bildschirmfoto 2018-08-14 um 14 20 52" src="https://user-images.githubusercontent.com/1155039/44091291-46f474ee-9fcd-11e8-9396-f79aa982187d.png">

For me it is not clear what the meaning of an *outlined* or *filled* version label is and why one of them has a drop shadow and the other one not

**Comment by grolu** [comment]
We could enable this by default, however we must not make too many columns visible by default to not break usability on smaller screen sizes. Moreover, the user always sees the version / upgrade button on shoot details page. For the filled / not filled button state I recommend reading the tooltip: Filled -highlighted- buttons indicate that there is a patch available. As patches should always be applied as soon as possible, this is highlighted. If a user does not uncheck the automatic updates during maintenance option, he will not see this state in most cases.

**Comment by grolu** [comment]
@vlerenc @holgerkoser @petersutter we should discuss which columns should be in enabled by default in our next UI sync.

**Comment by freegroup** [comment]
and the semantic of the drop shadow for the filled button?   :-)

**Comment by vlerenc** [comment]
Well, default columns is a big question. People want to focus on different things and that's why its configurable.

We have name, infrastructure, createdBy, createdAt, purpose, status, version, readiness, and actions (omitting the admin features).

If you need space, drop createdBy and createdAt. Why? Because it is not in our "educational interest". In said interest is that the users know and care for the infrastructure and region they are, what the purpose is (because it affects SLAs), status and version anyhow.

If you need more space, drop the readiness. Why? Because it's included/reflected in the status.

If you need more space, drop the actions. Why? Because it's in the details, except for the deletion that a.) is planned to be offered there anyhow (as per our sync before the last one) and it's a rare action.

That leaves name, infrastructure, purpose, status and version as bare minimum, which doesn't take that much space. As said, I would drop the actions only as last resort and generally, people may learn of the configurability rather late. Meaning, if we take it out, some of our users may never know, that we can show than the default columns.

That at least is my try to tackle the question rationally. As you know, I try to "recluse myself" from plain taste questions, because everybody has a different taste. From a rational perspective, I hope this makes some sense for the majority, at least.

**Comment by grolu** [comment]
Actually, the readiness is not reflected in the cluster status. We often see clusters with issues that have a green checkmark, as the status only reflects the last operation.

**Comment by vlerenc** [comment]
You are absolutely right, thank you for reminding me. However, at one point in time, we need to have a "more inclusive" status indicator. Not only because we plan to extend the list of `conditions`, which means, it won't be a sustainable strategy to show chips if the number of them grows. Now we have 3, we plan to include a fourth one and I can't tell right now, what the Gardener extensibility epic will bring. We must however expect a more fine-granular status representation with many more (not grouped/aggregated) `conditions` from different sources/controllers that at best can be aggregated into a single and overall health indicator. Future-wise, this may or may not be helpful for the Dashboard as any work on the chips may not pay off long term. The (single) status indicator is the thing will prevail, this way or another.
