### ISSUE TITLE
syntax checker indicator interpreted as "save button"

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#215]
The very prominent "button" at the bottom right of the editor is often interpreted as a save button. 
It is the absolute prominent element and thus gets into the main focus of the user.

I.e. you press the green button to save the YAML and wonder why it doesn't work.

<img width="1096" alt="bildschirmfoto 2018-10-15 um 10 40 16" src="https://user-images.githubusercontent.com/1155039/46939950-da735300-d067-11e8-997d-e70a5d0fd0da.png">

**Comment by grolu** [comment]
This "button" is not a syntax checker but gives you feedback, if the resource can be saved without conflicts or if it has changed in the meantime. There is a tooltip which explains the purpose of the icon. I currently do not have a better option on my mind and this is an "expert-mode" UI anyway. We currently do not plan to invest here as we want to focus on the formatted details screen and add management / configuration options there, see also: #139

**Comment by freegroup** [comment]
Why did you show this at all?

Inform the user if any problems occur during the save operation and provide 
a solution like:
 - Ignore and Save
 - Show me the Diff
 - Discard my changes

But confuse a user with such a prominent UI element is not the solution. And by the way, hover over all elements to explore the UI is not very comfortable..

Did you ever saw such an indicator in Google Docs or any other online tool?

**Comment by grolu** [comment]
The reason why we show this information to the user is because we know that the user will not be able to save this resource. Showing a diff to the user would be a feasible option. CodeMirror supports the option to show a diff to the user. However, this is currently not in scope. Showing the icon to avoid that the user continues to work on an outdated version, which he will never be able to save, was the easiest way to achieve a working solution. Therefore, it is intended that the icon is prominent. To quote myself: this is an expert-mode UI (which by the way needs to be confirmed by the user).
Currently, we do not have capacity to improve here. But this is an open source project - feel free to contribute.
