### ISSUE TITLE
Wrong last updated time shown

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#256]
Shoot's `.status.lastOperation.lastUpdateTime=2018-11-25T12:47:43Z`, the current time is `2018-11-25T13:35:24Z`. However, the Dashboard shows:

```
Shoot cluster state has been successfully reconciled.
an hour ago
```

although it's not one hour ago but ~48min.

**Comment by grolu** [comment]
We use the moment library to generate those texts. @petersutter I know that the library does not always shows exact times but tends to round to the next major unit. I have to further investigate.

**Comment by petersutter** [comment]
https://momentjs.com/docs/#/displaying/fromnow/

<img width="729" alt="screenshot 2018-11-26 at 15 57 33" src="https://user-images.githubusercontent.com/5526658/49021935-09670380-f194-11e8-8955-2eb06ff3fa79.png">

**Comment by Adracus** [comment]
Since https://github.com/gardener/gardener/pull/552, Gardener adds a `LastUpdateTime` to each condition, reflecting the last time the Shoot care controller worked on a condition - this might be the field to use to resolve this issue.

**Comment by grolu** [comment]
@Adracus the issue is related to the library we use to convert timestamps to human readable time information. The library rounds to the next entity and this means we lose information or accuracy. This needs to be discussed.
Concerning `LastUpdateTime` - we currently use `lastTransitionTime` to show when the condition state last changed. Should we change that (so that the user sees that the condition state was checked recently) - or should we stick to `lastTransitionTime`, which means that the user sees how long a condition has been in a good (or bad) state? What is your opinion on this.

**Comment by grolu** [comment]
@petersutter, @rfranzke
It is possible to set the thresholds, so it would be possible to influence the way momentjs renders the timestamps. So, if we set e.g. `s=60, m=60, h=24, d=30, m=12`, then *59 sec* would be rendered as *59 sec* and **not** *1 min*, *59 min* would be rendered as *59 min* and **not** *1 hour* and so on. This looks good in the first place, however, it turns bad with higher values. e.g. *1 year and 11 months* would be rendered as *1 year* and not *2 years*. I think you get the point. This is why they round up to the next unit by default. I do not see how we could improve - the only way would be to increase accuracy with something like *1 year, 11 months*. However, these values would use to much space in the list and also requires implementation effort. I think we stick to the default behavior of the lib. Exact time is shown as tooltip in the list anyway. We could also think about making the timestamp rendering configurable.

<img width="612" alt="screen shot 2019-01-29 at 08 36 15" src="https://user-images.githubusercontent.com/35373687/51894288-99e5de00-23a7-11e9-8ae3-14f7c825a652.png">

**Comment by grolu** [comment]
@adracus I changed the popper timestamp to show the last updated value. The last transition time is now shown in the popper title but only for conditions that are **not** in *good* state. Otherwise a user may asks why a condition is in good state for (only) some hours (as this implies there has been an error some hours ago). However, the condition may only toggled from *good* to *progressing* and back. See how this looks in the screenshots below:

<img width="797" alt="screen shot 2019-01-29 at 08 56 42" src="https://user-images.githubusercontent.com/35373687/51895663-03b3b700-23ab-11e9-893f-f8bb1e03baf3.png">
<img width="830" alt="screen shot 2019-01-29 at 08 56 32" src="https://user-images.githubusercontent.com/35373687/51895671-0adac500-23ab-11e9-8184-ecec4a56460f.png">

**Comment by grolu** [comment]
We also changed the way the Readiness tags are rendered - we now always show abbreviations (previously this did depend on the browser size which lead to some confusion). The shorter tags help us to use the space we have in the table more efficiently, as more conditions are to come. The full condition name is visible in the popper title and tooltip.

<img width="262" alt="screen shot 2019-01-29 at 08 56 14" src="https://user-images.githubusercontent.com/35373687/51895893-89376700-23ab-11e9-9ae4-c76414298904.png">

**Comment by petersutter** [comment]
Should we change `Last updated` to `Last checked`?

**Comment by grolu** [comment]
I don't know - `lastUpdated` is how Gardener labels the value in the condition. @adracus any thoughts?

**Comment by adracus** [comment]
@grolu the preview looks great! Regarding `Last updated` / `Last checked`: It's a Kubernetes convention to call it `LastUpdated` and for the advanced user it might be confusing to see a field `Last checked` that has no real 'reference' in the YAML file i.e. I'd vote for `Last updated` - But this is just my view as a technical person...
