### ISSUE TITLE
User complains about "no records" being found for their project, although project has many shoots

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#412]

**Comment by FGSHadden** [comment]
Multiple users reported over a few hour period that the Clusters tab page was displaying "No Data Available" refreshing the page and attempts via vpn/office/VDI networks all reported same error. We were unable to view cluster resources via the dashboard during this time. Approx 8am to 12pm Wednesday 19 June 2019 (10pm-2am UTC)

**Comment by grolu** [comment]
The behavior was caused by websocket connectivity issues. Currently, the dashboard uses both websocket and http based communication. When we switch to the new websocket implementation (see also #223) the dashboard will be websocket based only. In case of issues we will show an error page.
Reason for the websocket issues is still under investigation.

**Comment by grolu** [comment]
We had a look at the logs and it seems that the dashboard backend repeatedly lost connection to frontend clients (browser). This seems to have been caused by network issues. The behavior could not be reproduced.
