### ISSUE TITLE
Suppress Alertmanager Link (show msg instead) When Disabled/Not Deployed

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#423]
Monitoring doesn't deploy the alertmanager always since a couple of weeks. It does so only if an `alertTo` annotation is set. If it's not set, maybe we should either suppress the link or show an info msg instead, that there is no alertmanager, because the user has not configured to receive alerts.

**Comment by wyb1** [comment]
An Alertmanager is only deployed when the `garden.sapcloud.io/operatedBy` annotation is set as described in #396. We could consider removing the link to the alertmanager entirely since the UI is not very useful. I've only used the Alertmanager UI to debug alerts when defining them.

**Comment by holgerkoser** [comment]
The name of annotation is `garden.sapcloud.io/operatedBy`. We remove the link if this annotation is not set, correct? Should we also allow to set this annotation in the cluster create dialog / page? Currently all new clusters do not have an alertmanager.

**Comment by vlerenc** [comment]
@wyb1 Can I use the alert manager to show former alerts? Or is there really no value in it, since you also show alerts in the Grafana dashboards? If not, then we can keep it indeed very simple and drop it completely.

@holgerkoser I think it's OK/better, if we don't include it for new clusters, at least today. Let's first get get more experience with the overhauled alerts and exposed dashboards.

**Comment by wyb1** [comment]
You can't see alerts that fired in the past, only active and inhibited/silenced alerts. Old alerts are visible in Prometheus (and grafana). The only use for the Alertmanager UI is to silence alerts.

**Comment by vlerenc** [comment]
OK, then let's simplify this and remove the alert manager link in general from the Dashboard, since you (monitoring) suggest to drop it.

**Comment by dkistner** [comment]
I would not like to remove the alertmanager link in the dashboard, because it gives an user the option to silence individual alerts (always or just for a certain period of time). Why should we not provide quick access to this feature via the dashboard? That is probably interesting for the same people who requested the end-user monitoring, because there were also people which are interested in cluster related alerts. With the access to the alertmanager they can easily control by their own which alerts they want to receive.

We should check if a `Shoot` resource has the `garden.sapcloud.io/operatedBy` annotation and if the value of the annotation is a valid mail address, then we should display the alertmanager link in the dashboard.

In addition I would like to extend the cluster creation dialog to allow to set an alert receiver mail address. For sure we could wait with this until we have more trust in the alerts.
