### ISSUE TITLE
Start Cluster after Hibernation

### ISSUE THREAD

**Issue by CodeClinch** [gardener/dashboard#454]
**What would you like to be added**:
Currently, I have no cluster start button on the shoot overview (/namespace/garden-sectest/shoots/). I would like to have a start (after hibernation) button next to the delete button.

**Why is this needed**:
My clusters go into hibernation mode every evening. In the morning I have to go into each clusters details page to restart it again.

![Bildschirmfoto 2019-09-18 um 10 03 56](https://user-images.githubusercontent.com/40203931/65129581-ded48880-d9fb-11e9-8c3d-068cfa0f77c4.png)

**Comment by grolu** [comment]
I will close the issue as I see no point in implementing this feature. Waking up / hibernating clusters is a manual task that should not be necessary on a regular basis. As the @petersutter already pointed out this should be automated, please configure your hibernation schedule so that it fits your needs.
