### ISSUE TITLE
Search shoots does not work anymore

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#50]
In the shoot list, when trying to search for a shoot, nothing happens.
This seems to be related to this issue: https://github.com/vuetifyjs/vuetify/issues/3475
We probably have to filter in the vuex store.

**Comment by grolu** [comment]
As @petersutter pointed out, the bug was introduced when we turned on pagination in the v-data-table. We currently do not page, however use the pagination feature to sort items in the vuex store. Doing so, requires to implement the search functionality directly in the vuex store, too.
I added search functionality for the name column only, we can discuss to extend this in the future. Search supports multiple terms that will be ANDed to evaluate a match.
