### ISSUE TITLE
Add secret input validation

### ISSUE THREAD

**Issue by dansible** [gardener/dashboard#525]
We noticed in one of our Gardener projects that a user was able to set some invalid credentials. This caused the `xx.infra.tf-apply-xx` pod to fail with:

`Error: failed to start container "terraform": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"setenv: invalid argument\"": unknown`

Is it possible to add some parsing/checking for valid characters? (see attached)

![Screen Shot 2019-12-12 at 10 05 15 AM](https://user-images.githubusercontent.com/25449094/70698114-15eacb00-1cc7-11ea-921d-1ddf33bdb9c9.png)

**Comment by vlerenc** [comment]
We are considering that since 2 years. ;-) Right now, @timuthy is working on admission webhooks and we discussed the other day that it would be great to include it now, but let's see. We can't test the quotas/limits and we can't test the permissions, but at least whether a login would be possible for externally accessible infrastructures. As for the dashboard, I can't recall anymore whether regex checks could be added, do you @grolu ?

**Comment by grolu** [comment]
We have some basic checks in place for aws, the other infrastructures have more or less no validation as this is not really possible. If there would be an admission webhook that checks infrastructure secrets before creating them, this would solve this issue I guess.
