### ISSUE TITLE
Role based access to Kubeconfig in Dashboard

### ISSUE THREAD

**Issue by mikosa** [gardener/dashboard#556]
We are using the gardener service within SAP. It came to my attention that colleagues supporting gardener service can access the dashboard similar to users that are admin for a namespace, and download the kubeconfig of all clusters.
It would be a good option to have access to the kubeconfig based on roles instead, so that the owner of the cluster can decide to allow access to the kubeconfig only when needed. This is similar to other hyperscalers where access to a cluster need to be requested first to the admin of the cluster and then the admin would generate a new kubeconfig and give it the support team. At the end of troubleshooting, the admin can re-issue a new kubeconfig to cancel the previous kubeconfig.

**Comment by petersutter** [comment]
@mikosa currently, the kubeconfigs of your cluster are stored as secret in the garden cluster and the gardener operators have access to them. So yes they can access them using the dashboard, but also via CLI. 

cc @rfranzke as this feature request is not only limited to the dashboard. If we want to support this scenario other components are involved as well.

**Comment by vlerenc** [comment]
@mikosa Do not believe for a minute, AWS, Azure, or Google can't access your clusters, please. Even if we would do such a thing, we run the control plane. AWS, Azure, Google can and always will access your master(s) and we can and always will access your control plane pods as well. How else can they and we provide a managed service? You do not get a one-shot K8s installation, but a cluster we run updates on or repair or auto-scale for you. We can and always will have full administrative access and so do all the hyperscalers.

What we do work on is to offer an alternative to basic auth credentials and you can switch on OIDC for your cluster already today.

Again, the hyperscalers and we can and always will access your cluster at any point in time or else this would be no managed service. Hyperscalers and we simply have to do that in order to provide the service. If you don't want a managed service, you can only use tools like `kubeadm` and create the clusters yourselves, but then you also have to operate them. And even if you do that, the hyperscalers still have access. Yes, with TPM and the like, one or the other may have some additional barriers but at the end of the day, the hardware and your software runs in their DCs.

So, while role-based access control for project members is a thing, cutting off the operators of the managed service is not, because then it wouldn't be a managed service anymore.

**Comment by vlerenc** [comment]
Let's close this one. Having roles is planned to be described/worked on in #553.
