### ISSUE TITLE
Better error message for the enduser

### ISSUE THREAD

**Issue by PadmaB** [gardener/dashboard#63]
Below is the error message in one of the node failure case

![image](https://user-images.githubusercontent.com/2491252/39039710-a43139a6-44a3-11e8-85a7-5c80ec9efcb3.png)

However, the message is quite technical exposing the details of the machine and the shoot cluster info whic h is not transparent to the end user. So, the message is confusing and less helpful.

Or am I missing something?

**Comment by vlerenc** [comment]
Not sure how to improve that easily. The Dashboard shows only the technical error messages it receives, i.e. MCM could change the message directly.

What the Dashboard can't easily do is to map all different technical error messages to end-user error messages. We had the issue also in the SCP Cockpit.

If we want that, we need to open a larger epic, but this would mean:
- All components must agree on error messages and register them centrally
- All error messages require an ID
- All error messages have a human readable text assigned
This is a large undertaking (it would give us I18N as a side effect). However, it's still a lot of effort.

On the other hand, the effort may not be justified, because the Dashboard is anyways an operator tool that we have only temporarily exposed to SAP end users for now. When the SCP Cockpit offers Kubernetes clusters, we will close it for end users and focus even more on ops and Open Source/community and they will prefer a less tightly coupled error handling/accept technical error messages.
