### ISSUE TITLE
Allow setting of IOPS for AWS Worker-groups

### ISSUE THREAD

**Issue by AndreasBurger** [gardener/dashboard#677]
**What would you like to be added**:
Currently, the Dashboard only allows the configuration of the Volume Type (`gp2` or `io1`) for workers on AWS shoot. For both volume types, there is however the possiblility to provide a value for the desired IOPS using the shoot-spec.
It'd be nice if this configuration could also be done through the Dashboard's `Configure Workers` dialog.

**Why is this needed**:
Makes the configuration of these values easier for end-users. Also, in case of `io1` a value has to be given, so additional hints/verifications could be added here.

**Comment by petersutter** [comment]
https://github.com/gardener/gardener-extension-provider-aws/pull/71

**Comment by grolu** [comment]
@rfranzke @vlerenc Is this something that we want to expose on the Dashboard UI? Is this setting important enough that configuring via UI is not sufficient? I ask this question because we do not want to flood the worker configuration with options. But we certainly can add this filed if the use case is there (as we did for several Open Stack options)

**Comment by rfranzke** [comment]
Hm, you expose the volume type already, and IOPS is a mandatory field when `io1` is selected. Hence, it makes sense to either expose it or to remove the dropdown menu for the volume type.

**Comment by grolu** [comment]
Okay makes sense. I will add the field.
