### ISSUE TITLE
 Issue in accessing Dashboards 

### ISSUE THREAD

**Issue by K7king** [gardener/dashboard#70]
The new gardener canary dashboard was inaccessible from  Firefox browser.
In chrome its accessible.

**Comment by petersutter** [comment]
![firefox network screenshot](https://user-images.githubusercontent.com/5526658/39239401-07842b2c-4881-11e8-821c-ae691fb1f5df.png)

establishing a websocket connection failed as the certificate was rejected by the browser. Could not reproduce on my machine with firefox. However, user reported that the issue is resolved meanwhile.
