### ISSUE TITLE
Hide managed field and last-applied-configuration in yaml editor.

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/dashboard#935]
**What would you like to be added**:

Remove the fields `.metadata.managedFields` and annotation `last-applied-configuration` when using the yaml editor.

**Why is this needed**:

Better user experience.

The Shoot's `.metadata.managedFields` decreases the user-experience when using the yaml editor of the Shoot cluster.
Similar to the `last-applied-configuration` annotation.

These are only fields that are for Gardener-internal purposes (server side-apply) & almost always not interesting to Shoot owners.

**Comment by grolu** [comment]
This should be an easy thing to do. But maybe we should just hide them (by default) with a checkbox, something like _hide Gardener internal fields_, so that the user can enable them and understands why they are not visible while they are present in the shoot yaml if inspected with other tools.
What do the others think about this?

**Comment by danielfoehrKn** [comment]
@vasu1124

**Comment by vpnachev** [comment]
I would completely hide them, just like `kubectl edit` is doing it https://github.com/kubernetes/kubernetes/pull/91946

**Comment by vasu1124** [comment]
indeed, I also recommend hiding these fields. Seems we could apply the same approach as  https://github.com/kubernetes/kubernetes/pull/96878
