### ISSUE TITLE
Cannot choose Terminal Target of a cluster when opening the terminal a second time

### ISSUE THREAD

**Issue by uvwild** [gardener/dashboard#946]
**What happened**:
Once I opened a terminal to a specific target. the target selector remembers the target and does not let me choose another one.

**What you expected to happen**:
Maybe I want to choose a different target the next time - like most of the times?
I dont want this selection to be chosen for me - EVER!

**How to reproduce it (as minimally and precisely as possible)**:
open terminal to a target. close open again 

**Anything else we need to know**:
deleting cookies die not help.
closing all dashboard windows and logging in again DOES help.
therefore it seems to be stored in the context of the session.

**Environment**:
ubuntu-20.04
firefox 85.0

**Comment by petersutter** [comment]
Hi @uvwild,

this is a feature and is by design. We restore all terminal sessions if they were not cleaned up in the meantime (e.g. after 5 minutes).
Maybe you haven't noticed the x (close button) to close the terminal session?
<img width="2170" alt="2021-02-08_16-37-27" src="https://user-images.githubusercontent.com/5526658/107242583-6c1edf80-6a2c-11eb-9bf1-143ad0a8dd76.png">
You can also open additional session when clicking on the menu button in the upper right corner of the pane or use one of the keyboard shortcuts
<img width="1252" alt="2021-02-08_16-42-50" src="https://user-images.githubusercontent.com/5526658/107242958-d768b180-6a2c-11eb-80cf-6c23ec151b5f.png">

**Comment by uvwild** [comment]
yes the top right button i see before but did not expect it to open another type of terminal.

I was expecting that  an exit of the terminal is enough to kill the session. it also ask me to terminate. Thats the normal behaviour in a linux terminal window.

That I have to press an additional button is not obvious :) 
Good we talked about it!
Thank you for the clarification!

**Comment by petersutter** [comment]
We are spinning up a pod to which the browser attaches to. When the browser is closed, the pod still runs for some time until it is finally cleaned up by the `terminal-controller-manager` if it does not receive heartbeats anymore.
That's why we made it explicit to "kill" the terminal session by clicking the (x) button.
