### ISSUE TITLE
select ops-toolbelt image according to shoot infra type

### ISSUE THREAD

**Issue by jfortin-sap** [gardener/dashboard#977]
**What would you like to be added**:
select ops-toolbelt image according to shoot infra type

**Why is this needed**:
to speed up loading time and minimize network bandwidth consumption

This ops-toolbelt PR introduced a feature to provide a docker image per infra type for the ops-toolbelt image.
https://github.com/gardener/ops-toolbelt/pull/43

Based on discussions with Peter, I would suggest at a high level we introduce logic to basically rewrite the ops-toolbelt image configuration variable in the configuration based on a known infra type list, if it does not match than default to configuration variable that points to the default image one-size fits all image.

**Comment by petersutter** [comment]
@jfortin-sap with https://github.com/gardener/ops-toolbelt/issues/37#issuecomment-810058915 an ops-toolbelt image matrix (infrastructure x kubectl version) should be build. So the kubectl version should also be considered in addition to the infrastructure

**Comment by jfortin-sap** [comment]
@petersutter To minimize build times regarding supporting many kubectl versions per infra img, it seems a common sense approach the dashboard helm chart for opstool-belt could inject the kubectl version inside the docker image. Thoughts?

          image: eu.gcr.io/gardener-project/gardener/ops-toolbelt:latest
          env:          
            - name: "kubectlv"
              value: "1.21"

**Comment by petersutter** [comment]
@jfortin-sap, I'm not sure if I could follow your proposal. 
Would this mean that the `kubectl` binary is not baked into the image but rather the `ops-toolbelt` would download `kubectl` in a specific version during runtime according to the `kubectlv` environment variable?

**Comment by jfortin-sap** [comment]
@petersutter Yes, thoughts?

**Comment by petersutter** [comment]
This would mean, that even though the image is cached on the node, it would always download around 46MB for new containers of the ops-toolbelt.

Could you give more details on how this works? At which point in time will the kubectl be downloaded?

Is the environment variable really needed? If you anyhow fetch the `kubectl` version during runtime, you could also figure out the current version of the `kube-apiserver` and then download the proper `kubectl` version

### Alternatives:

#### Hybrid apporach
We could still pre-bundle `kubectl` into `ops-toolbelt` with a reasonable version that works for the latest kubernetes versions.

>`kubectl` is supported within one minor version (older or newer) of `kube-apiserver`.
>Example:
>
>kubectl is supported at 1.22, 1.21, and 1.20

https://kubernetes.io/docs/setup/release/version-skew-policy/

E.g. if `1.22` is the latest `kube-apiserver`, we could bundle the `ops-toolbelt` with `kubectl` version 1.21 which would work for 1.22, 1.21 and 1.20. If the `kube-apiserver` has a different version than the supported version skew, the correct `kubectl` version could be downloaded.

#### Pre-bundle approach leveraging version skew
Similar to the hybrid approach we would create different `ops-toolbelt` images with pre-bundled `kubectl` versions. We make use of the supported version skew of 3 minor releases.
So for example to cover `kube-apiserver` versions from 1.13 - 1.21 (9 minor releases) we would need `ops-toolbelt` versions with `kubectl` versions
- 1.14 (covering 1.13, 1.14, 1.15)
- 1.17 (covering 1.16, 1.17, 1.18)
- 1.20 (covering 1.19, 1.20, 1.21)

**Comment by vlerenc** [comment]
@jfortin-sap Is there a problem to provide this matrix of images (IaaS CLI x `kubectl` version)?

Downloading dynamically `kubectl` seems to me like a waste of time (SRE/DevOps) and money (networking costs, though probably negligible in relation to the time I don't want to waste on waiting for `kubectl` to be downloaded and installed, especially in web terminals, but also in general). We have build automation to cover that kind of image matrix without much effort on our side, I would think?

While @petersutter is right to point out the skew policy and possible options, I would think it's not worth it. In the end, it must be trivial to build and launch the right toolbelt image and considering the skew policy in build and launch makes things more complicated. Since we anyways should have the matrix built automatically, I would think it's a lot easier to just built all the images and be done with it.

**Comment by jfortin-sap** [comment]
Ok, pre-bundled images for each infra type / kubectl version. Which kubectl versions do we want to support or not support?

**Comment by vlerenc** [comment]
@jfortin-sap Did you clarify yet?

Basically, all that we currently support in Gardener, at least 1.15 through 1.21. It should follow a clear pattern so that Dashboard and `gardenctl` can pick the right one without mapping table (1:1).

Also, we should clarify how to auto-propose PRs with the latest `kubectl` version/fixes... or shall we run the build job automatically once per week?

**Comment by jfortin-sap** [comment]
@vlerenc It's in progress. I'm working on the PR, sorting out some pipeline build issues.
